
project_id = "ifxvwettmgixfbivlzzl"

[functions.whatsapp-scheduler]
verify_jwt = false

[functions.instance-manager]
verify_jwt = false

[functions.cleanup-expired-trials]
verify_jwt = false

[functions.create-whatsapp-instance]
verify_jwt = false

[functions.get-whatsapp-qr]
verify_jwt = false

[functions.check-whatsapp-status]
verify_jwt = false

[functions.sync-whatsapp-groups]
verify_jwt = false

[functions.send-immediate-message]
verify_jwt = false

[functions.manage-instance-lifecycle]
verify_jwt = false
